Merge Tokel specific development efforts by Dimxy
KomodoPlatform/komodo pull request #467
Opened 2021-07-14 21:25 UTC by NutellaLicka

Added:
Many TokensV2 updates, bug fixes, and some new Tokel specific RPCs
AssetsV2 optimisations & bug fixes
Oracles dust fix
New "Tokel Standard" token data format for both NFT's and fixed supply tokens (evalcode 0xf7, CC 247)
New royalty feature to tokens for any trades conducted through assets ask/bid transactions.

2021-07-15 17:09 UTC, dimxy approved these changes
as I am the dev I approve it

2021-07-15 20:21 UTC, jmjatlanta reviewed
All of what I've found are minor issues that are more for clarity, with (almost) zero effect on runtime. On the next pass I will focus on functionality. A couple of notes:
- Comments should be comments. Dead code should be removed. The old code will remain in GitHub's history if needed later.
- Replacing `NULL` with `nullptr` is a good idea. It is for more than just readability.
- It can be difficult to spot problems on long lines. About 118 characters max will show on 1 line in GitHub without horizontal scrolling.

2021-07-15 20:21 UTC, jmjatlanta commented on src/cc/heir.cpp
> +        if (TotalPubkeyNormalInputs(NULL, mtx, myPubkey) < amount && TotalPubkeyCCInputs(NULL, mtx, myPubkey) < amount)
Using `nulllptr` reduces ambiguity.

2021-07-15 20:21 UTC, jmjatlanta commented on src/cc/old/CCassetstx_v0.cpp
> +            return FinalizeCCTx(0, cpTokens, mtx, mypk, txfee,
can `mask` (line 320) be removed? Also may be able to be removed elsewhere in this file (lines 508, 585, 682).

2021-07-15 20:21 UTC, jmjatlanta commented on src/cc/old/CCtokens_v0.cpp
> +			return FinalizeCCTx(0, cp, mtx, mypk, txfee, EncodeTokenOpRet(tokenid, voutTokenPubkeys, std::make_pair((uint8_t)0, vopretEmpty)));
Remove `mask` (line 859)

2021-07-16 20:17 UTC, jmjatlanta requested changes
Most are minor, some are opinions. 1 is a segfault, albeit probably rare.

2021-07-16 20:17 UTC, jmjatlanta commented on src/init.cpp
> +        fprintf(stderr,"nLocalServices %llx %d, %d\n",(long long)nLocalServices,GetBoolArg("-addressindex", DEFAULT_ADDRESSINDEX),GetBoolArg("-spentindex", DEFAULT_SPENTINDEX));
Perhaps use a logger here (if it is initialized).

2021-07-16 20:17 UTC, jmjatlanta commented on src/rpc/tokensrpc.cpp
> -    if (fHelp || params.size() > 0)
tokenid not used.

2021-07-22 10:46 UTC, dimxy commented
I have gone through all of those above notes and made improvements/cleanups. Thank you @jmjatlanta 
(ofc there are still much to improve yet)

2021-07-27 10:19 UTC, merged

2021-07-27 17:41 UTC, jmjatlanta reviewed
The recent changes look good. I rank this one important: 
https://github.com/KomodoPlatform/komodo/pull/467/files?file-filters%5B%5D=.cpp&file-filters%5B%5D=.h&file-filters%5B%5D=.include&file-filters%5B%5D=.py&file-filters%5B%5D=.sh&file-filters%5B%5D=No+extension#r671461098

I am getting an assertion with komodo-test. It may be my environment, or something that has already been fixed:
```
./src/komodo-test --gtest_filter=TestAddrmanTests.addrman_simple
Note: Google Test filter = TestAddrmanTests.addrman_simple
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from TestAddrmanTests
[ RUN      ] TestAddrmanTests.addrman_simple
komodo-test: addrman.cpp:160: void CAddrMan::ClearNew(int, int): Assertion `infoDelete.nRefCount > 0' failed.
```

2021-07-27 17:41 UTC, jmjatlanta commented on src/cc/CCassetsCore_impl.h
> +    if( n == 0 || (vintxFuncId = A::DecodeAssetTokenOpRet(vintx.vout.back().scriptPubKey, evalCode, assetid, price, origpubkey, expiryHeight)) == 0 ) {
If you used vintx.vout.size() == 0 here `n` would no longer be required.